# Generated by Django 4.2 on 2023-04-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_vacancy_type_of_employment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_industry', to='product.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('company_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_type', to='product.companyindustry')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIndustrySubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('company_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_subtype', to='product.companyindustrytype')),
            ],
        ),
    ]
