# Generated by Django 4.2 on 2023-04-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_companyindustry_companyindustrytype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyindustrysubtype',
            name='company_subtype',
        ),
        migrations.RemoveField(
            model_name='companyindustrytype',
            name='company_type',
        ),
        migrations.AddField(
            model_name='companyindustrysubtype',
            name='industry_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='product.companyindustrytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyindustrytype',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='product.companyindustry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyindustry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='product.company'),
        ),
    ]
