# Generated by Django 4.2 on 2023-05-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_institute_education'),
        ('product', '0013_remove_resume_knowledge_of_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about_me',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(blank=True, to='catalog.education'),
        ),
    ]
