# Generated by Django 4.2 on 2023-05-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_education_specialization'),
        ('product', '0014_resume_about_me_remove_resume_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='knowledge_of_languages',
            field=models.ManyToManyField(blank=True, to='catalog.languageskill'),
        ),
    ]
