# Generated by Django 4.2 on 2023-05-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_nativelanguage_remove_languageskill_is_native_and_more'),
        ('product', '0015_alter_resume_knowledge_of_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='native_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='native_language', to='catalog.nativelanguage'),
            preserve_default=False,
        ),
    ]
