# Generated by Django 4.2 on 2023-05-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_resume_native_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')]),
        ),
    ]
