# Generated by Django 4.2 on 2023-05-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_education_specialization'),
        ('product', '0019_alter_vacancy_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='knowledge_of_languages',
            field=models.ManyToManyField(blank=True, to='catalog.languageskill'),
        ),
    ]
