# Generated by Django 4.2 on 2023-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_jobexperience_remove_employmentatcompany_company'),
        ('product', '0020_alter_vacancy_knowledge_of_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='employment_at_company',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='job_experiences',
            field=models.ManyToManyField(blank=True, to='catalog.jobexperience'),
        ),
    ]
