# Generated by Django 4.2 on 2023-05-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_resume_employment_at_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.CharField(blank=True, null=True),
        ),
    ]
