# Generated by Django 4.2 on 2023-04-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
    ]
