# Generated by Django 4.2 on 2023-04-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_reviews_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
