# Generated by Django 4.2 on 2023-04-29 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_companyindustrysubtype_company_subtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0007_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyUnwanted',
            new_name='UnwantedCompany',
        ),
        migrations.RenameModel(
            old_name='VacancyUnwanted',
            new_name='UnwantedVacancy',
        ),
    ]
