# Generated by Django 4.2 on 2023-04-29 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_companyindustrysubtype_company_subtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0008_rename_companyunwanted_unwantedcompany_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_sp', to='product.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_sp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
