# Generated by Django 4.2 on 2023-05-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('feedback', '0009_favoritespecialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='vacancy',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='catalog.company'),
        ),
        migrations.AlterField(
            model_name='unwantedcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_unwanted', to='catalog.company'),
        ),
        migrations.DeleteModel(
            name='FavoriteSpecialization',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
