# Generated by Django 4.2 on 2023-05-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountify', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_company',
            field=models.BooleanField(default=False),
        ),
    ]
