# Generated by Django 4.2 on 2023-05-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountify', '0004_alter_user_groups_alter_user_user_permissions'),
        ('accountify', '0004_user_can_create_company'),
    ]

    operations = [
    ]
