# Generated by Django 4.2 on 2023-05-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_institute_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='institute',
        ),
        migrations.AddField(
            model_name='education',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='catalog.institute'),
            preserve_default=False,
        ),
    ]
