# Generated by Django 4.2 on 2023-05-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_education_institute_education_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education_specialization', to='catalog.specializationsubtype'),
            preserve_default=False,
        ),
    ]
