# Generated by Django 4.2 on 2023-05-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_education_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagelevel',
            name='code',
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='name',
            field=models.CharField(choices=[('A1', 'A1 -- Начальный'), ('A2', 'A2 -- Элементарный'), ('B1', 'B1 -- Средний'), ('B2', 'B2 -- Средне-продвинутый'), ('C1', 'C1 -- Продвинутый'), ('C2', 'C2 -- В совершестве')], max_length=128),
        ),
    ]
