# Generated by Django 4.2 on 2023-05-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_language_name_language_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kg', 'Кыргызский'), ('ru', 'Русский'), ('en', 'Английский'), ('fr', 'Французский'), ('de', 'Немецкий'), ('es', 'Испанский'), ('it', 'Итальянский'), ('pt', 'Португальский'), ('pl', 'Польский'), ('uk', 'Украинский'), ('tr', 'Турецкий'), ('zh', 'Китайский'), ('ja', 'Японский'), ('ko', 'Корейский'), ('ar', 'Арабский'), ('he', 'Иврит'), ('hi', 'Хинди'), ('ur', 'Урду')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='languageskill',
            name='is_native',
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('kg', 'Кыргызский'), ('ru', 'Русский'), ('en', 'Английский'), ('fr', 'Французский'), ('de', 'Немецкий'), ('es', 'Испанский'), ('it', 'Итальянский'), ('pt', 'Португальский'), ('pl', 'Польский'), ('uk', 'Украинский'), ('tr', 'Турецкий'), ('zh', 'Китайский'), ('ja', 'Японский'), ('ko', 'Корейский'), ('ar', 'Арабский'), ('he', 'Иврит'), ('hi', 'Хинди'), ('ur', 'Урду')], max_length=2),
        ),
    ]
