# Generated by Django 4.2 on 2023-05-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_nativelanguage_remove_languageskill_is_native_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_specialization', to='catalog.specialization'),
        ),
    ]
