# Generated by Django 4.2 on 2023-05-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_jobexperience_remove_employmentatcompany_company'),
        ('product', '0021_remove_resume_employment_at_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='EmploymentAtCompany',
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='catalog.company'),
        ),
    ]
