# Generated by Django 4.2 on 2023-05-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_delete_experience_delete_employmentatcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_specializations', to='catalog.specializationsubtype'),
            preserve_default=False,
        ),
    ]
