# Generated by Django 4.2 on 2023-05-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='can_create_vacancy',
            field=models.BooleanField(default=False),
        ),
    ]
