# Generated by Django 4.2 on 2023-04-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_email',
            field=models.BooleanField(default=True),
        ),
    ]
